### ISSUE TITLE
USB Insuccifient memory?

### ISSUE THREAD

**Issue by theoparis** [futurelucas4502/projectsandcastle-install-scripts#2]
The following error occurs after booting checkra1n and running the linux python script  with sudo:
```bash

Waiting for device...
Loading device tree...
Device tree loaded successfully.
Loading kernel...
Traceback (most recent call last):
  File "/home/theo/dev/projectsandcastle-install-scripts/linux/./load_linux.py", line 71, in <module>
    dev.write(2, kernel, 1000000)
  File "/usr/lib/python3.9/site-packages/usb/core.py", line 989, in write
    return fn(
  File "/usr/lib/python3.9/site-packages/usb/backend/libusb1.py", line 837, in bulk_write
    return self.__write(self.lib.libusb_bulk_transfer,
  File "/usr/lib/python3.9/site-packages/usb/backend/libusb1.py", line 938, in __write
    _check(retval)
  File "/usr/lib/python3.9/site-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 12] Insufficient memory
``` 

I have an iphone 6s, does this mean the iphone is not capable of having enough ram?  Or could it be that it doesn't have enough disk space?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/futurelucas4502/projectsandcastle-install-scripts/issues/2#issue-1010379712

@theoparis, see https://github.com/corellium/projectsandcastle/pull/41#issuecomment-2149301486.
